### PR TITLE
fix: Change default config to consider sourceType as module

### LINKED ISSUE #558: Parse error analysing Typescript files with default configuration
This error is presented in every typescript file that uses an import statement.
`Cause: Parsing error: ImportDeclaration should appear when the mode is ES6 and in the module context.`

Example of code that triggers this error:

```typescript
import { A } from "module";

console.log(A)
```

### PR DESCRIPTION
**Pull request by franciscodua**
This will accept module specific typescript syntax, such as import statements.
Added multiple tests for scenarios that could be affected (JSON, typescript with imports)

Fixes #558

### CODE REVIEW

File: src/convertResults.ts [hunk 1]
```diff
@@ -11,12 +11,6 @@ export function convertResults(report: CLIEngine.LintReport): ToolResult[] {
     const messages = result.messages
     const fatalErrors = messages
       .filter((m) => m.fatal)
-      // this filter is here to avoid errors related to files not supported by current parser
-      // example: Using a "@typescript-eslint/parser" parser does not allow JSON files to be analyzed
-      .filter(
-        (m) =>
-          !m.message.includes("The file does not match your project config:")
-      )
```
Comment (lolgab) [inline src/convertResults.ts:19]: Why did you remove this part?

**Review by lolgab — CHANGES_REQUESTED** [review]

File: src/convertResults.ts (hunk 1 above)
Comment (franciscodua) [reply src/convertResults.ts:19]: I think we don't need it anymore now that we filter out typescript patterns for other file types.
https://github.com/codacy/codacy-eslint/commit/d182d03278f62001118d46a61a192488e78e3557#diff-8ebafde9572c134640c7265425ec4eefR61
Do you think we should keep it anyways?

Comment (lolgab) [reply src/convertResults.ts:19]: So you're saying that we are maintaining the workaround rate constant, again..?
Cool!

**Review by lolgab — APPROVED** [review]
LGTM 👍
