### PR TITLE
fix: Add manual unnamedParams to docGenerator

### LINKED ISSUE #47: Missing option field in rule "Quotes"
After recent upgrade of version, the rule "Quotes" no longer give the option to edit the type of quote to take in consideration for the analysis.
```
 "parameters": [
        {
          "name": "unnamedParam",
          "default": "double"
        }
      ]
```
More information: https://eslint.org/docs/rules/quotes

### PR DESCRIPTION
**Pull request by lolgab**
Fixes #47

### CODE REVIEW

File: src/docGenerator.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ import { toolName, toolVersion } from "./toolMetadata"
 import { writeFile } from "./fileUtils"
 import { capitalize, patternTitle } from "./docGeneratorStringUtils"
 import { Rule } from "eslint"
```
Comment (josemiguelmelo) [inline src/docGenerator.ts]: I would put external dependency import before relative dependencies

Comment (lolgab) [reply src/docGenerator.ts]: Added eslint plugin to sort imports 👌
